image:
  repository: docker.io/jevzib/icc-webui
  tag: "latest"

service:
  port: 8000

oracle:
  host: oracle-db.icc.svc.cluster.local
  port: 1521

env:
  DJANGO_SETTINGS_MODULE: "icc_webui.settings"
  DJANGO_ALLOWED_HOSTS: "icc-webui.local,localhost,127.0.0.1"

ingress:
  enabled: true
  host: icc-webui.local
