apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: root-app-directory-approach
  name: applications
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: argoproj.io
    jsonPointers:
    - /status
    kind: Application
  project: default
  source:
    path: appofapps
    repoURL: https://github.com/jevzib/gitops.git
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - allowEmpty=true
    - CreateNamespace=true
