apiVersion: v1
kind: Secret
metadata:
  name: icc-webui-fernet
  labels:
    argocd.argoproj.io/secret-type: cluster
  namespace: icc
type: Opaque
stringData:
  FERNET_KEY: "akFOt-QqaHr_RB0u2vOJaQE1iCZOUfkcOxox3LSJyyY="
