apiVersion: v1
kind: Secret
metadata:
  name: oracle-credentials
  labels:
    argocd.argoproj.io/secret-type: cluster
  namespace: icc
type: Opaque
stringData:
  ORACLE_USER: "ccp"
  ORACLE_PASSWORD: "mypassword"
