apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:jevzib/gitops.git
    path: testing/apps
    targetRevision: main
  destination:
    name: kind-testing
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

