apiVersion: v1
kind: Service
metadata:
  name: {{ include "icc-webui.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
  selector:
    app: {{ include "icc-webui.name" . }}

