apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: icc-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jevzib/gitops.git
    path: testing/apps/secrets
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: icc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
