apiVersion: v1
kind: Service
metadata:
  name: oracle-db
  labels:
    app: oracle-db
spec:
  type: ExternalName
  externalName: {{ .Values.oracle.host }}
  ports:
    - port: {{ .Values.oracle.port }}
      targetPort: {{ .Values.oracle.port }}
